### PR TITLE
README: completed instruction to enable Jayatana

### PR DESCRIPTION
**Pull request by nick87720z**
From this instruction:
https://askubuntu.com/questions/687919/how-to-make-java-gui-programs-look-more-modern

### CODE REVIEW

**Comment by nick87720z** [comment]
Just looked into its sources inside vala-panel, there is another option - JAYATANA.
 Both variables are found only in one place (./lib/com_jarego_jayatana_Agent.c, line 156):
```
        // la libreria si existe iniciar procedo de validacion de integracion
        if (com_jarego_jayatana_Agent_CheckEnv("JAYATANA", "1", true) ||
            com_jarego_jayatana_Agent_CheckEnv("JAYATANA_FORCE", "true", true))
        {
```
Did not look deeper for what, but it seems, that only both variables are working.
However, i have global menu without either, with just _JAVA_OPTIONS.
What they are used for?

**Comment by rilian-la-te** [comment]
For forcing jayatana. It was be necessary for non-Unity. For now, it can be used to disable jayatana for specific apps.

**Comment by nick87720z** [comment]
I could run jsampler with disabled appmenu, only with this:
`$ JAYATANA=0 JAYATANA_FORCE=0 jsampler`
omiting any of these variables make it not working (this was expected after looking to above code).
I propose to leave only one of these working. Or even more - why not just use UBUNTU_MENUPROXY, as on all other toolkits?

**Comment by nick87720z** [comment]
So, what about a little options change? For now it is like if you specify just one option, you PC think, you are unsure... some very secure system, requiring two keys in to turn on).
Also, UBUNTU_MENUPROXYis well known as long as unity's dbusmenu/appmenu system.

**Comment by nick87720z** [comment]
Looks like typo - it just should accept both 1 or true values.

**Comment by nick87720z** [comment]
I just noticed, that jayatana, as well as qt appmenu variants, have different global menu style, and qt variant doesn't event have any on/off control variable.
For now left JAYATANA_FORCE for jayatana, just fixed typo (unfortunally not type in commit text)).

**Comment by rilian-la-te** [comment]
Ok, this is acceptable.

**Pull request merged**
