### PR TITLE
Make menubar scrollable

### PR DESCRIPTION
**Pull request by nick87720z**
Fixes problem, when too long menubar pushes other applets out of panel.
For now it is completed only for xfce4-panel. Applets for other panels need own ways to become expanded.
For now on non xfce4 panel it will shrink to minimum possible size, though still capable to scroll.

Scrolling step for now is fixed 20.
Though it could determine it by width of sample string, being rendered with font/size, used by menubar.

For now i got only one case - audacity 2.2.0 or higher with enabled extra menus.

### CODE REVIEW

**Comment by rilian-la-te** [comment]
I need a screen and details of the bug. I think, another solution should be preferred.

**Comment by nick87720z** [comment]
For now i found it simplest for coding...
https://youtu.be/tVGJwGTKEAc
Other, probably better, variant, could be with continuation button, opening extra menus in popup menu. My first experience, writing vala)

**Comment by rilian-la-te** [comment]
1. I do not like a scroller built-in in widget, especially if it will mess vala-panel behaviour for applet (vala-panel is primary target, not xfce4-panel)
2. You can do compact switching (for example - found very large menu - switched to compact edition).

**Comment by rilian-la-te** [comment]
For me, Russian audacity fits perfectly)))
screenshot at 2017-12-19 08-50-04

**Comment by nick87720z** [comment]
No problem with vala-panel - it defines event handling only for widget class. So even if it is in same process, nothing else affected - e.g., scroling volume control works as always.
Screen res: 1600x900.

All-in-one menu button would be nice, at least because it was in gnome global menu, and is now in plasma5 appmenu applet. But it is sompletely different style. Not, that if menu doesn't exceed free space, as on your screenshot, nothing changes. Difference appears only when menu overgrows.

Yet, xfce4-panel gtk3 version introduced one issue - for both widgets, ported to gtk3, and panel itself: all context menus, including labels on panel itself (involves main menu, dir menu, system tray, date&time and... vala-panel-appmenu) have bold text. Those, still on gtk2 (places for me), use regular font. You can notice this on posted video: though you did not set it bold, as i see on vala-panel, xfce4-panel forces it. As result, it is a bit wider. Did not inspect this issue yet, there might be way to lock on regular font.

Screenshot

**Comment by rilian-la-te** [comment]
Build vala-panel-appmenu with your patch, and show me screen with it and vala-panel (not xfce4-panel!). If it works correctly, I can integrate it.

**Comment by nick87720z** [comment]
If you tell, how to make VP plugin to expand...
I found it quickly for xfce panel (in vapi it is set_expand(true)), but not for vala-panel. Searching through vala-panel C headers, i found some 'expand' words, but don't know, how to use it for panel plugin. And is it for plugin or only for panel itself.

Without it applet shrinks down to width of first entry - window name, which includes windows list of same class + create new/close window entries.

**Comment by rilian-la-te** [comment]
ValaPanel expand is desktop entry based. Look to desktop file of expandable plugin such as xfce-tasklist. But expand is not good for me, I think than menu should not expand.

**Comment by nick87720z** [comment]
This is how it looks without expanding.
[There panel was started during leafpad focused](https://i.imgur.com/DKA9QKl.gifv)
[Restarted with focused desktop, some other apps](https://i.imgur.com/aD72IkK.gifv) (note, that it keeps initial width on window switch)
[Separately for geany editor](https://i.imgur.com/2885PN7.gifv)

**Comment by nick87720z** [comment]
Now expands for vala-panel too! )
vala-panel-audacity-1
vala-panel-audacity-2
Imho, in horizontal mode expanding would be rather expected.
Same case, as for taskbars (window lists).

**Comment by rilian-la-te** [comment]
Who are you like expand?

**Comment by rilian-la-te** [comment]
And app name should not be scrolled, it is not good. So, you should modify MenuWidget, not Menubar.

**Comment by nick87720z** [comment]
I tried to add this line to appmenu.desktop.plugin.in.
After reinstallation i have /usr/lib64/vala-panel/applets/appmenu.plugin with same line,
but it doesn't work - applet is not expanded.

**Comment by rilian-la-te** [comment]
You should enable expanding in config:-) and return set_hexpand)))

**Comment by nick87720z** [comment]
Oh, i did not know, that it has config dialog. Vala-panel doesn't indicate, that it is available)
Btw, i can't update submodules for vala-panel:
```
git submodule update
error: Server does not allow request for unadvertised object 1f03e9960c788e3ad9cf17c0ae21aa7f93999b81
Fetched in submodule path 'lib/dbusmenu', but it did not contain 1f03e9960c788e3ad9cf17c0ae21aa7f93999b81. Direct fetching of that commit failed.
```

**Comment by rilian-la-te** [comment]
force to fetch latest revision))

**Comment by nick87720z** [comment]
There is still one issue, which i can't beat, appearing on xfce4/mate panels, but not on vala-panel. Due to hardness of keeping scrolling wiht Viewport directly, i moved it to ScrolledWindow. As result, it auto-magically installs all even handling for self, with smooth scrolling support. Thanks to all this job, but on xfce4/mate panels all incoming events have their delta_x/delta_y props =0.0, while in vala-panel it gives useful values. However, this behavior happens only for mouse. When scrolling is done by touchpad (e.g. 2-finger scrolling), all ok for xfce4/mate panels too.

While GtkViewport was used for entire widget, it followed event masks, explicitly modified by add_events(). But for ScrolledWindow, as i found, both SCROLL_EVENT and SMOOTH_SCROLL_EVENT are unset.

**Comment by rilian-la-te** [comment]
> There is still one issue, which i can't beat, appearing on xfce4/mate panels, but not on vala-panel.

It is beacuse vala-panel uses in-process applets, but XFCE or MATE builds out-off-process by default.

I will try to build your branch on vala-panel and prove correctness. If it will works correctly, I may integrate scroller with adjustments.

**Comment by nick87720z** [comment]
Right after last push i tried it with mate-plugin - menubar part shrinks to zero, though before before these commits all was ok.

**Comment by nick87720z** [comment]
Yeah, forgot about hexpand. Btw, it seems all these changes affect only gtk appmenu. Others, like qt or jayatana, have non-bold app name, no scrolling (pushing other applets as usually)... though private style from appmenu.css is still used, because i was right - >=xfce4-panel-4.13 sets default text font to bold, and this is what i tried to fix.

And about bold text: as far as i saw, proper cmake option is called BOLD_APPMENU, what means, that only app name must be forced bold when set, but in this case all menus were. Btw, by some reason css modificator :first-child did not work, as well as some other... failed to get these styles working.

What is place, you told not working in gtk 3.10? (i don't find any exact link, only same for all posts to single page with all changes). There are so much versions changed - can't believe, 3.10 still in use. Minimal version, i found in zugaina overlays, 3.14::leio :/ .

After all, i just improved existing code base... did not know about MenuWidgetDbusmenu yet).
Scrolling... since you told, only menubar must be scrollable, i added its code, as was obvious for me, in place, where menubar object is created and added to its parent. Is not it logical?
However, before it was in Appmenu class, and there entire menu was scrolled. And did not think about supporting current code base with such old gtk (i heared, there are enough incompatibilities even besides css-like language).

**Comment by nick87720z** [comment]
Is it possible, to get text style from global style, bypassing modifications from host panel?

**Comment by nick87720z** [comment]
Today i discovered, that total bold font in xfce panel was caused by theme, which set it for most known panels, including xfce, budgie, unity, but not mate and vala-panel (this is why they both had non-bold font). With adwaita and ambiance class styles default font is regular.

I propose, instead of using static style text, get actual numeric font weight, then multiply it by some factor (applying some limit, to still keep it readable), and use this value in style... might be implemented with some printf-like function (i don't know, is it possible to use dynamic variable for format string, so this might need to move css content inside sources).

**Comment by nick87720z** [comment]
Now it should work for all menu kinds. The only problem, is that bug #163 now happens with probablity close to 100% (before it might not crash severla times each after other).

**Comment by nick87720z** [comment]
For now merge is completed (until more commits in upstream).
After all my changes the only code difference is in menu-widget.vala.
ScrolledWindow is kept persistant, and only menus are recreated on each change.
Style context is applied directly in set_menu() without apply_style(), because current css implementation, with "first-child", doesn't work, since menubar is now wrapped by Gtk.ScrolledWindow (however, css itself works unchanged).
set_menu() funcs are fixed to destroy existing menubar widgets even with null argument, to match completion flags state change, they do in this case.
And about menu autoscrolling: i prefer to treat it rather as essential part of scrolling itself, because simple adding of menubar to scrolledwindow is not enough to make it working similar to Gtk.IconBox. After all, it is separate commit. Of course, if you insist, it is no work to revert. You could try in action both with this commit or prior version.

**Pull request merged**
