### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wesleyotugo**
Added description on how to get support for both gtk and Qt

### CODE REVIEW

**Comment by rilian-la-te** [comment]
Please, make README cross-platform, if you want.

**Comment by rilian-la-te** [comment]
See my changes now. This will be closed.

**Comment by wesleyotugo** [comment]
`export UBUNTU_MENUPROXY=libappmenu.so`

libappmenu.so des not exist in /usr/lib only the version vala-panel-appmenu & xfce-appmenu library

**Comment by rilian-la-te** [comment]
Yes, I know. It is from appmenu-gtk package

**Pull request closed without merging**
