### PR TITLE
Started french translation

### PR DESCRIPTION
**Pull request by quent1-fr**
Started translating appmenu in french (work in progress, I'll certainly need more context).

### CODE REVIEW

**Comment by rilian-la-te** [comment]
Please, regenerate pot.

**Comment by rilian-la-te** [comment]
Or wait for me, I will do it today

**Comment by rilian-la-te** [comment]
applications-system is icon name, you can replace it, but I recommend just copy it)

**Comment by quent1-fr** [comment]
Yup, found that after the PR. I've regenerated the POT locally and fixed two errors in language strings. 
Seems that ../lib/mate-plugin-appmenu.vala:43 and ../lib/xfce4-plugin-appmenu.vala:56 are both missing a closing parenthesis in "Use Compact mode (all menus in application menu)".

**Comment by rilian-la-te** [comment]
Will look for it.

**Comment by rilian-la-te** [comment]
You lose desktop strings, not good.

**Comment by quent1-fr** [comment]
Damn. I'll cancel this PR then recreate one once you'll have updated the POT file.

**Comment by rilian-la-te** [comment]
Ok, will do it ASAP.

**Comment by rilian-la-te** [comment]
You may continue, pot is updated.

**Pull request closed without merging**
