### PR TITLE
Update PKGBUILD

### PR DESCRIPTION
**Pull request by wesleyotugo**
Added libappindicator as dependencies , which function is  "A library for passing menus over DBus "

### CODE REVIEW

**Comment by rilian-la-te** [comment]
1. It is incorrect, because it will work with any unity-gtk-module around, and any appmenu-qt5 around.
2. libappindicator should be in optional depends, not in makedepends.

**Comment by wesleyotugo** [comment]
1. Doesn't your unity package provide the only unity-gtk-module in arch apart from Unity-For-Arch, so it is not likely to be around
2. Sorry, i have corrected it now

**Comment by rilian-la-te** [comment]
It works with Unity-For-Arch, so I think it is better to keep. My standalone module should provides it anyway.

**Comment by wesleyotugo** [comment]
So it should be added as depend to install, because they are going to install it regardless.. Could save a stroke or  two.

**Comment by rilian-la-te** [comment]
Not to depend, some programs work without it anyway:))) Some machines won't have GTK2 or GTK3 or QT for example. So, it is optional dependencies.

**Comment by rilian-la-te** [comment]
And not add depends to XFCE package only. Mirror it also to vala-panel package.

**Comment by wesleyotugo** [comment]
@rilian-la-te If the chrome and chromium and vlc of this world does not work i do not know what will, also with most apps being created using electron like wordpress etc .. It does not break anything what we need    is the package and the compilation of this dependencies goes without a hitch.
EDIT: Checking out importance of libindicate or libdbusmenu

**Pull request closed without merging**
